### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by raupachz** [matinh/vdldoc-maven-plugin#1]
Hi there,

could you provide a litte usage page in the README? I am unsure how integrate this plugin.

Thanks in advance :)

**Comment by matinh** [comment]
Hi!

On 20 Dez 2017, Björn Raupach wrote:

> Hi there,
> 
> could you provide a litte usage page in the README? I am unsure how integrate this plugin.

You mean like this?
http://matinh.github.io/vdldoc-maven-plugin/usage.html

hth,
- martin

**Comment by raupachz** [comment]
Exactly! Thanks. Didn't see that one. ;)
