### ISSUE TITLE
Single Vdldoc page for multi module maven project

### ISSUE THREAD

**Issue by codelano** [matinh/vdldoc-maven-plugin#2]
Hi, please suggest how can I use your plugin to generate single page for multi module maven project?
Currently if I generate vdldoc for my project, multiple vdldoc pages creates for each separate maven module.

**Comment by matinh** [comment]
This is currently not supported by underlying vdldoc and thus not supported by the plugin. No plans from my side to implement this.

**Comment by codelano** [comment]
Ok, how about using maven site? Where URL appends in maven generated site?

**Comment by matinh** [comment]
Sorry, I currently have no clue how to do it and I don't have time to look at it.
